### ISSUE TITLE
Java error: UnsupportedClassVersionError

### ISSUE THREAD

**Issue by YoannUniKS** [equinor/neqsimpython#159]
Dear all,

I updated neqsim to the last version (2.4.0) and got the following error:

>  java.lang.java.lang.UnsupportedClassVersionError: java.lang.UnsupportedClassVersionError: neqsim/thermodynamicOperations/ThermodynamicOperations has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I am using the last version of the JRE (8 Update 341) on windows 10, so I'm not sure what causes this error. I have looked on the internet, and have not found a proper solution for this error so far.

I rolled back the previous versions of neqsim and found that the error appears from version 2.3.26 onwards.

Any hint will be welcome!

Thanks in advance.

Best regards

**Comment by EvenSol** [comment]
Hi.
The most recent versjons og neqsim Python requires Java 11+. See requirements:

Java version 11 or higher ([Java JDK](https://adoptium.net/)) needs to be installed. The Python package [JPype](https://github.com/jpype-project/jpype) is used to connect Python and Java. Read the [installation requirements for Jpype](https://jpype.readthedocs.io/en/latest/install.html). Be aware that mixing 64 bit Python with 32 bit Java and vice versa crashes on import of the jpype module. The needed Python packages are listed in the [NeqSim Python dependencies page](https://github.com/equinor/neqsimpython/network/dependencies).

**Comment by YoannUniKS** [comment]
Thank you very much, it works after installing OpenJDK. The JRE is not suited for the last NeqSim releases (only works until 2.3.25).
