### ISSUE TITLE
Issue with ammonia in pipe function

### ISSUE THREAD

**Issue by Ahmedhassan676** [equinor/neqsimpython#188]
Hello dear developers ! thanks for your wonderful work and amazing library!
I'm trying to use the pipe function in NeqSim and it's doing well but when i try to add ammonia into the stream it returns an error.
y code is as follows:
def NeqSim_calculations(q,D,df_comp,t,p1,p2,L,type):
        if type == 'estimate quantity': 
            p1 = p1*98.066*0.01
            p2 = p2*98.066*0.01
            q = q*24/(1000000)
            #Creating inlet fluid using SRK-EoS   
            names =  list(df_comp.index.str.lower())
            molefractions = list(df_comp['mol%']*0.01)
            fluid1 = createfluid2(names, molefractions)
            fluid1.setMixingRule('classic')
            fluid1.setTemperature(t, "C")
            fluid1.setPressure(p1, "bara")
            fluid1.setTotalFlowRate(q, "MSm3/day")
            
            TPflash(fluid1)

            

            deltaElevation = 0.0
            pipeLength = L
            roughness= 0.00005
            diameter = D
            error = 10
            method = "friction theory"
            fluid1.getPhase('gas').getPhysicalProperties().setViscosityModel(method)
            fluid1.initProperties()
            while error > 0.01:
                fluid1.setTotalFlowRate(q, "MSm3/day")
                clearProcess()
                
                stream1 = stream(fluid1)
                
                pipeSimple = pipe(stream1, pipeLength, deltaElevation, diameter, roughness)
                runProcess()
                
                
                error = abs(p2 - pipeSimple.getOutStream().getFluid().getPressure('bara'))
                if p2 - pipeSimple.getOutStream().getFluid().getPressure('bara') > 0.01:
                    q = q - q*0.01
                elif p2 - pipeSimple.getOutStream().getFluid().getPressure('bara') < -0.01:
                    q = q + q*0.01
                else: error = error
                result = q*1000000/24
          return result
error message when i try to add "ammonia" is:
  File "/home/appuser/venv/lib/python3.9/site-packages/neqsim/thermo/thermoTools.py", line 100, in createfluid2

    return fluidcreator.create2(JString[:](names), JDouble[:](molefractions), unit)

java.lang.java.lang.RuntimeException: java.lang.RuntimeException: neqsim.util.exception.InvalidInputException: PhaseSrkEos:init - Input totalNumberOfMoles must be larger than zero.

i checked for the operating conditions i assumed and was fine as p1=1 bara p2= 0.6 bara, t =45 C 

Could someone please guide me to add ammonia to my code? Thanks!

**Comment by EvenSol** [comment]
Hi.
We are working on adding ammonia to the database. It will be implemented soon, as well as the possibility to easier add new components (new database solution). 

https://github.com/equinor/neqsim/pull/604

**Comment by Ahmedhassan676** [comment]
Thanks!
